IF
  Global("RandomBeenSet6582990","%DurlagsTower_D4%",0)
THEN
  RESPONSE %spawnRem%
    SetGlobal("RandomBeenSet6582990","%DurlagsTower_D4%",1)
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
RESPONSE %spawnPerc%
    Continue()
END
//Spawnpoint % code above

IF
  RandomNum(1,1)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",0)
  Global("RandomBeenSet6582990","%DurlagsTower_D4%",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet6582990_0","%DurlagsTower_D4%",1)
    SetGlobal("RandomBeenSet6582990","%DurlagsTower_D4%",1)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(0)
  TimeOfDay(3)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END



IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),1,LEVEL)
  CheckStat(StrongestOf(Myself),1,LEVEL2)
  CheckStat(StrongestOf(Myself),1,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),1,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #60
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #50
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),2,LEVEL)
  CheckStat(StrongestOf(Myself),2,LEVEL2)
  CheckStat(StrongestOf(Myself),2,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),2,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #25
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #25
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    CreateCreature("ZG#SMELI",[658.2990],0)  // Lightning Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEAI",[658.2990],0)  // Air Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStat(StrongestOf(Myself),3,LEVEL)
  CheckStat(StrongestOf(Myself),3,LEVEL2)
  CheckStat(StrongestOf(Myself),3,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),3,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),4,LEVEL)
  CheckStat(StrongestOf(Myself),4,LEVEL2)
  CheckStat(StrongestOf(Myself),4,LEVEL3)
  CheckStat(StrongestOf(Myself),5,LEVEL)
  CheckStat(StrongestOf(Myself),5,LEVEL2)
  CheckStat(StrongestOf(Myself),5,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),5,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    CreateCreature("ZG#SMEFI",[658.2990],0)  // Fire Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    CreateCreature("ZG#SMEDU",[658.2990],0)  // Dust Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    CreateCreature("ZG#SMESM",[658.2990],0)  // Smoke Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    CreateCreature("ZG#SMEIC",[658.2990],0)  // Ice Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    CreateCreature("ZG#SMEOO",[658.2990],0)  // Ooze Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(6)
  CheckStat(StrongestOf(Myself),6,LEVEL)
  CheckStat(StrongestOf(Myself),6,LEVEL2)
  CheckStat(StrongestOf(Myself),6,LEVEL3)
  CheckStat(StrongestOf(Myself),7,LEVEL)
  CheckStat(StrongestOf(Myself),7,LEVEL2)
  CheckStat(StrongestOf(Myself),7,LEVEL3)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  !CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(1)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(2)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(3)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #20
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(4)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(5)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #10
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END
IF
  Range([PC],35)
  OR(2)
  TimeOfDay(1)
  TimeOfDay(2)
  NumInParty(6)
  OR(3)
  CheckStatGT(StrongestOf(Myself),7,LEVEL)
  CheckStatGT(StrongestOf(Myself),7,LEVEL2)
  CheckStatGT(StrongestOf(Myself),7,LEVEL3)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
  Global("RandomSet6582990_0","%DurlagsTower_D4%",1)
THEN
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #15
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    CreateCreature("ZG#SMEMA",[658.2990],0)  // Magma Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #30
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    CreateCreature("ZG#SMEMS",[658.2990],0)  // Mist Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    CreateCreature("ZG#SMEMN",[658.2990],0)  // Mineral Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
  RESPONSE #5
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    CreateCreature("ZG#SMEST",[658.2990],0)  // Steam Mephit
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",EIGHT_HOURS)
END

IF
  !Range([PC],35)
  Global("SpawnReset6582990","%DurlagsTower_D4%",1)
  GlobalTimerExpired("05146582990","%DurlagsTower_D4%")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",0)
    SetGlobal("RandomBeenSet6582990","%DurlagsTower_D4%",0)
    SetGlobal("RandomSet6582990_0","%DurlagsTower_D4%",0)
END

IF
  Range([PC],35)
  Global("SpawnReset6582990","%DurlagsTower_D4%",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset6582990","%DurlagsTower_D4%",1)
    CreateCreature("GHOULLOR",[658.2990],0)  // ~Greater Ghoul~
    SetGlobalTimer("05146582990","%DurlagsTower_D4%",2400)
END
